version: '3.8'

services:
  rust-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rust-server
    ports:
      - "9092:9092"
    volumes:
      - ./config/cluster.json:/app/config/cluster.json
    depends_on:
      - redis-node-1
      - minio
    environment:
      RUST_LOG: debug
      KAFKA_HOST: "0.0.0.0"
      KAFKA_PORT: 9092
      KAFKA_LOG_STORE_TYPE: s3
      KAFKA_LOG_STORE_S3_BUCKET: mybucket
      KAFKA_LOG_STORE_S3_PREFIX: logs
      KAFKA_LOG_STORE_S3_ENDPOINT: http://minio:9000
      KAFKA_LOG_STORE_S3_ACCESS_KEY: minioadmin
      KAFKA_LOG_STORE_S3_SECRET_KEY: minioadmin
      KAFKA_META_STORE_TYPE: redis
      KAFKA_META_STORE_REDIS_URLS: redis://redis-node-1:7001,redis://redis-node-2:7002,redis://redis-node-3:7003
      KAFKA_INDEX_STORE_TYPE: redis
      KAFKA_INDEX_STORE_REDIS_URLS: redis://redis-node-1:7001,redis://redis-node-2:7002,redis://redis-node-3:7003

  redis-node-1:
    image: redis:7
    container_name: redis-node-1
    command: ["redis-server", "--port", "7001", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    ports:
      - "7001:7001"
    volumes:
      - redis-data-1:/data

  redis-node-2:
    image: redis:7
    container_name: redis-node-2
    command: ["redis-server", "--port", "7002", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    ports:
      - "7002:7002"
    volumes:
      - redis-data-2:/data

  redis-node-3:
    image: redis:7
    container_name: redis-node-3
    command: ["redis-server", "--port", "7003", "--cluster-enabled", "yes", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    ports:
      - "7003:7003"
    volumes:
      - redis-data-3:/data

  redis-cluster-init:
    image: redis:7
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
    entrypoint: >
      sh -c "sleep 10 && echo yes | redis-cli --cluster create redis-node-1:7001 redis-node-2:7002 redis-node-3:7003 --cluster-replicas 0"

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Console UI
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

  minio-init:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      sh -c "
        sleep 5 &&
        mc alias set local http://minio:9000 minioadmin minioadmin &&
        mc mb local/mybucket || true
      "
volumes:
  minio-data:
  redis-data-1:
  redis-data-2:
  redis-data-3: